# NOTE: Only Windows Server 2012 supported at this time
os: Windows Server 2012

# NOTE: That platform relates to msbuild NOT the host OS platform
platform:
    - Win32    
configuration:
    - Release

# Use shallow clone for speed as we only need the last commit to build     
shallow_clone: true
clone_depth: 1

environment:
    global:
        CYG_ROOT: C:/cygwin
        CYG_MIRROR: http://cygwin.mirror.constant.com
        CYG_CACHE: C:/cygwin/var/cache/setup
        INSTALL_FOLDER: C:\monoinstall
#    matrix:
#        - 
#            CYG_ARCH: x86

# Only build specific branches as master is unlikely to build
branches:
    only:
      - mono-3.10.0-branch

init:
    - 'echo Building Mono for Windows'
    - 'echo System architecture: %PLATFORM%'

install:
    - 'echo Retrieving Cygwin'
    - 'appveyor DownloadFile http://cygwin.com/setup-x86.exe -FileName setup.exe'
    - 'echo Setting up Cygwin dependencies'
    - 'setup.exe -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P autoconf -P automake -P bison -P gcc-core -P gcc-g++ -P mingw-gcc -P libtool -P make -P python -P gettext-devel -P gettext -P intltool -P libiconv -P pkg-config >NUL'
    - 'echo Check Cygwin setup'
    - '%CYG_ROOT%/bin/bash -lc "cygcheck -dc cygwin"'

# NOTE: Mono msbuild doesn't work at present so use Cygwin to build
#build:
#    project: C:\projects\mono\msvc\mono.sln 
#    verbosity: detailed

build_script:
    - 'echo Cygwin root is: %CYG_ROOT%'
    - 'echo Build folder is: %APPVEYOR_BUILD_FOLDER%'
    - 'echo Installation folder is: %INSTALL_FOLDER%'
    - 'mkdir %INSTALL_FOLDER'
    - 'echo Autogen running...'
    - '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; ./autogen.sh --prefix=$INSTALL_FOLDER --with-preview=yes"'
    - 'echo Configure running...'
    - '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; ./configure --host=i686-pc-mingw32"'
    - 'echo Make running...'
    - '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; make"'

